package session

import (
	"strings"
	"testing"
	"time"
)

func TestParseNetscapeBasic(t *testing.T) {
	input := `# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by Example. Edit at your own risk.

.google.com	TRUE	/	TRUE	1900000000	__Secure-1PSID	abc123
#HttpOnly_.google.com	TRUE	/	TRUE	1900000000	SID	def456
.google.com	TRUE	/	FALSE	0	SESSION_TMP	ephemeral
`
	cookies, err := ParseNetscapeString(input)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(cookies) != 3 {
		t.Fatalf("want 3 cookies, got %d: %+v", len(cookies), cookies)
	}

	psid := cookies[0]
	if psid.Name != "__Secure-1PSID" || psid.Value != "abc123" {
		t.Errorf("unexpected psid: %+v", psid)
	}
	if !psid.Secure || psid.HttpOnly {
		t.Errorf("secure/httponly wrong on non-#HttpOnly line: %+v", psid)
	}
	if psid.Expires == nil || psid.Expires.Unix() != 1900000000 {
		t.Errorf("expires not parsed: %v", psid.Expires)
	}

	sid := cookies[1]
	if !sid.HttpOnly {
		t.Errorf("HttpOnly prefix not recognized: %+v", sid)
	}
	if sid.Name != "SID" {
		t.Errorf("name corrupted by prefix strip: %q", sid.Name)
	}

	tmp := cookies[2]
	if !tmp.Session || tmp.Expires != nil {
		t.Errorf("expiry=0 should mean session cookie: %+v", tmp)
	}
}

func TestParseNetscapeIgnoresBlankAndCommentLines(t *testing.T) {
	input := "\n\n# comment\n\n.google.com\tTRUE\t/\tTRUE\t1900000000\tA\t1\n# trailing\n"
	cookies, err := ParseNetscapeString(input)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(cookies) != 1 || cookies[0].Name != "A" {
		t.Fatalf("unexpected result: %+v", cookies)
	}
}

func TestParseNetscapeRejectsMalformedLine(t *testing.T) {
	// 3 fields is unambiguous garbage.
	input := ".google.com\tTRUE\t/\n"
	_, err := ParseNetscapeString(input)
	if err == nil {
		t.Fatal("expected error on malformed line")
	}
	if !strings.Contains(err.Error(), "tab-separated fields") {
		t.Errorf("error message should identify field count: %v", err)
	}
}

func TestParseNetscapeTolerates6FieldLineForEmptyValue(t *testing.T) {
	input := ".google.com\tTRUE\t/\tTRUE\t1900000000\tEMPTY_VALUE\n"
	cookies, err := ParseNetscapeString(input)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(cookies) != 1 || cookies[0].Name != "EMPTY_VALUE" || cookies[0].Value != "" {
		t.Errorf("6-field empty-value line mis-parsed: %+v", cookies)
	}
}

func TestParseNetscapeExpirySignConsistent(t *testing.T) {
	now := time.Now().Unix()
	input := ".google.com\tTRUE\t/\tTRUE\t" + itoa(now+3600) + "\tFUT\tv\n"
	cookies, err := ParseNetscapeString(input)
	if err != nil || len(cookies) != 1 || cookies[0].Expires == nil {
		t.Fatalf("parse: %v %+v", err, cookies)
	}
	if cookies[0].Expires.Unix() != now+3600 {
		t.Errorf("expiry off by %d", cookies[0].Expires.Unix()-(now+3600))
	}
}

func itoa(n int64) string {
	return fmtInt(n)
}

// fmtInt is a tiny wrapper so we don't import strconv in tests (keeps test
// file lean). Not performance critical.
func fmtInt(n int64) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
